language: go
sudo: true
go:
  - 1.10.x
before_install:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D4284CDD
  - echo "deb https://repo.iovisor.org/apt/xenial xenial main" | sudo tee /etc/apt/sources.list.d/iovisor.list
  - echo "deb http://mirror.servers.com/ubuntu/ xenial main restricted universe" | sudo tee /etc/apt/sources.list.d/xenial.list
  - echo "deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe" | sudo tee /etc/apt/sources.list.d/xenial.list
  - sudo apt-get update && sudo apt-get install -y bcc-tools clang gcc binutils libbcc-examples libncurses5-dev linux-headers-$(uname -r)
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/bpfd-linux-amd64
          - cross/bpfd-linux-amd64.md5
          - cross/bpfd-linux-amd64.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "JHWc1VWTVL+vyKWN52N98tmgC4s0HbSRgtKg2K7ntWpD43c1dqLdZL0+LkZ60NMHM6scn3Uzg8pzb+5/5KcoDZQAfsSIsoB6xBwg/A2JP9REyiQvmmSmojTsgGswHGmwAkpRCWhzB6j2wQkjbUamxPX96EFcFxYiIG0Pci1oiV/QNHvvFyMpC3VaU4Z/x//yrvz+RgV2atyJ4M3UYTL1vovIFI2o7mH6cbESt/R3tSGDj3g9bHYeZp7cx5aszbYUCfixONhK5v4oV2s1diATO7btsG/TGvWzTmfrANRUsNcSl//zBRkgMy3HWsYqxwMIqwKasNtY6U+2sJVdQ1kbLwyYz5AIvwcaX8O2Ov6py2YjaF54YYjfbeyx0t4+663Hsg4FFQLWvWxbYxkM/FETYYOVND4057bkGis5dc01+sAEUoBIiAWFyS5SU6Sv9ELIuUsCOoxGxXHfKohfQY2Z+P7w5e26nAv10TF+LjdcnoPSNm9ro/Xm6gU2ioLWuZoqCIAleEQIgzA1nAnaBgioRkSLbVmnBUg5DyT/8btRHN+nMcJobvHcIrk62lUlocJAQ0Imlj4AMQHoIBt3t2mB5jHNdZ7R2coVf7HGIW06B5qjV92qtLUKjTWvBV5I6JfDhJZyjc/MCs/PEpMhzPnZOQWIOCmeDUkqGW0mWVZDKIY="
