tracer = "open"

actions = ["stdout"]

[filterEvents]
  # file_access
  [filterEvents.filename]
  # match
  values = ["/etc/shadow", "/etc/sudoers", "/etc/pam.conf"]
  # command_execution
  [filterEvents.command]
  values = ["sudo"]
