[[rule]]
program = "exec"

[searchEvents]
  [searchEvents.cmdline]
  values = ["sshd", "dbus-daemon-lau", "ping", "ping6", "critical-stack-", "pmmcli", "filemng", "PassengerAgent", "bwrap", "osdetect", "nginxmng", "sw-engine-fpm", "start-stop-daem"]

[filterEvents]
  containerRuntimes = ["docker","kube"]
